/**
 * Phase 2 — Apply PubChem CIDs to seed.ts
 *
 * Reads the JSON report generated by enrich-pubchem.ts and writes resolved
 * CIDs back into lib/dictionary/seed.ts. Run this AFTER reviewing the
 * enrichment report.
 *
 * Usage:
 *   npx tsx scripts/apply-cids.ts          # write CIDs to seed.ts
 *   npx tsx scripts/apply-cids.ts --dry    # preview changes without writing
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

// ── Types ────────────────────────────────────────────────────────────────────

type ReportEntry = {
  normalized: string;
  cid: number | null;
  cid_resolved_via: string | null;
};

type Report = {
  summary: Record<string, unknown>;
  results: ReportEntry[];
};

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  const dry = process.argv.includes('--dry');
  const reportPath = resolve(__dirname, 'output', 'pubchem-report.json');
  const seedPath = resolve(__dirname, '..', 'lib', 'dictionary', 'seed.ts');

  // Validate inputs
  if (!existsSync(reportPath)) {
    console.error(`[apply-cids] Report not found: ${reportPath}`);
    console.error('[apply-cids] Run "npx tsx scripts/enrich-pubchem.ts" first.');
    process.exit(1);
  }

  const report: Report = JSON.parse(readFileSync(reportPath, 'utf-8'));
  const cidEntries = report.results.filter((r) => r.cid !== null);

  if (cidEntries.length === 0) {
    console.log('[apply-cids] No CIDs to apply.');
    return;
  }

  console.log(`[apply-cids] Found ${cidEntries.length} resolved CIDs in report`);

  let seedContent = readFileSync(seedPath, 'utf-8');
  let applied = 0;
  let skipped = 0;

  for (const entry of cidEntries) {
    // Skip entries that already have a pubchem_cid in seed.ts
    // Look for the normalized key line and check if pubchem_cid follows nearby
    const normalizedEscaped = entry.normalized.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const blockPattern = new RegExp(
      `(normalized:\\s*'${normalizedEscaped}',\\n)`,
    );

    const match = seedContent.match(blockPattern);
    if (!match) {
      console.log(`[apply-cids] ⚠ Could not find entry for "${entry.normalized}" in seed.ts — skipping`);
      skipped++;
      continue;
    }

    // Check if pubchem_cid already exists for this entry (within ~15 lines after normalized)
    const matchIndex = seedContent.indexOf(match[0]);
    const blockSlice = seedContent.slice(matchIndex, matchIndex + 600);
    if (blockSlice.includes('pubchem_cid:')) {
      if (dry) {
        console.log(`[apply-cids] · ${entry.normalized} — already has pubchem_cid, skipping`);
      }
      skipped++;
      continue;
    }

    // Find the health_risk_tags line for this entry and insert pubchem_cid after it
    // Pattern: "    health_risk_tags: [...],\n" → insert "    pubchem_cid: <CID>,\n" after
    const tagsLinePattern = new RegExp(
      `(normalized:\\s*'${normalizedEscaped}',[\\s\\S]*?health_risk_tags:\\s*\\[[^\\]]*\\],\\n)`,
    );
    const tagsMatch = seedContent.match(tagsLinePattern);

    if (!tagsMatch) {
      console.log(`[apply-cids] ⚠ Could not find health_risk_tags for "${entry.normalized}" — skipping`);
      skipped++;
      continue;
    }

    const insertion = `    pubchem_cid: ${entry.cid},\n`;
    seedContent = seedContent.replace(tagsMatch[0], tagsMatch[0] + insertion);
    applied++;

    if (dry) {
      console.log(`[apply-cids] + ${entry.normalized} → CID ${entry.cid} (via "${entry.cid_resolved_via}")`);
    }
  }

  console.log(`\n[apply-cids] ${dry ? 'Would apply' : 'Applied'}: ${applied} CIDs`);
  console.log(`[apply-cids] Skipped: ${skipped}`);

  if (!dry) {
    writeFileSync(seedPath, seedContent);
    console.log(`[apply-cids] ✓ Written to ${seedPath}`);
  } else {
    console.log('[apply-cids] Dry run complete — no files modified.');
  }
}

main();
